
version: '3.8'

services:
  thread:
    build: .
    container_name: thread
    ports:
      - "9003:9003"
    environment:
      SPRING_DATASOURCE_URL: ${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

networks:
  backend:
    external: true
    name: project_backend